### ISSUE TITLE
Please do a collaboration with Geertjan

### ISSUE THREAD

**Issue by Chris2011** [Everlaw/nbts#1]
Hey, as you can see it here, he is still working on such thing too: https://github.com/GeertjanWielenga/TypeScript please connect together or give them as a pull request to the repo or whatever.

**Comment by Chris2011** [comment]
And here is his blog: https://blogs.oracle.com/geertjan/entry/ecmascript_typescript_and_netbeans_ide

**Comment by jeffrey-easyesi** [comment]
I just looked at that project; I think we are working in different directions.

My approach is to re-use the TypeScript language service code (src/services/ in the TypeScript source) as much as possible. This gives a lot of functionality with a relatively small amount of implementation effort. The downside is that it is written in TypeScript itself rather than Java, so it needs to be run via an external JS interpreter (nodejs).

I'm not sure exactly what the planned design is for the other project, but based on the presence of the ES6 grammar, it would appear they intend to parse and analyze TypeScript code in Java. This is much more ambitious - an ES6 grammar will get you pretty far towards a TypeScript parser, but when it comes to type analysis, pretty much all of checker.ts (15,731 lines of code) would have to be rewritten in Java.

As far as I know, all current TypeScript IDE plugins re-use the language service, except for JetBrains who have implemented their own parser and analyzer in Java (it's proprietary, alas).

**Comment by geekdenz** [comment]
Although we may have been working in a different direction, I think rather than developing 2 projects with the same goal it makes sense to join our efforts.

Your code completion is much further along and having tested it briefly, it seems fast enough to use a nodejs process/service.

So, I can offer to help implement features. It would be nice if you or other people could add issues that they find important to implement and then we can look at the issues and implement in order of importance.

**Comment by GeertjanWielenga** [comment]
I agree with Jeffrey.
