### ISSUE TITLE
Better and Easier Build

### ISSUE THREAD

**Issue by geekdenz** [Everlaw/nbts#13]
At the moment, every time I check out the project, I have to manually add a couple of module dependencies. It would be good if that were not the case. It is a manual process that is annoying. I believe that just a few minor changes to the nbproject folder solves this issue.

I will make a pull request to fix this problem if it does.

**Comment by jeffrey-easyesi** [comment]
These modules don't exist in the current version of NetBeans (8.0.2); I get an error trying to build with your change:
```
/home/jeffrey/netbeans-8.0.2/harness/build.xml:174: No dependent module org.netbeans.modules.parsing.indexing
BUILD FAILED (total time: 0 seconds)
```

**Comment by geekdenz** [comment]
Oh. It's in NetBeans 8.1RC. Maybe you have earlier versions of the modules and could just redo the steps I did:

 - Clone the repository into a new directory.
 - Open in your NetBeans.
 - Resolve module issues by right-clicking on the hints in the marked classes and
 - Choosing "import module".

Should be straight-forward and only take 5 minutes of your time.

**Comment by jeffrey-easyesi** [comment]
It looks like 8.1 reorganized some modules, causing source-incompatible changes:
* [openide.util split into openide.util and openide.util.base](http://hg.netbeans.org/main/rev/e596998fec11)
* [parsing.api split into parsing.api and parsing.indexing](http://hg.netbeans.org/main/rev/57ef0bc28d58)
* [openide.util renamed to openide.util.ui, openide.util.base renamed to openide.util](http://hg.netbeans.org/main/rev/6d0e84b1f867)

8.0.2 doesn't just have earlier versions of `parsing.indexing` and `openide.util.ui`; it doesn't have them at all, their classes being part of `parsing.api` and `openide.util`.

If I build the plugin on 8.0.2 (without the new module dependencies), the .nbm works on both 8.0.2 and 8.1RC2; it looks like NetBeans has a "Automatic Dependencies" system so that plugins declaring dependencies on only the old modules will still work. However, if I build the plugin on 8.1RC2 (with the new module dependencies added), the resulting .nbm will *not* install on 8.0.2:

![screenshot from 2015-10-18 00 08 14](https://github-cloud.s3.amazonaws.com/assets/3847609/10565767/c36f9b24-758d-11e5-933a-2b232322bce0.png)

8.0.2 is the latest released version so the plugin needs to work on it, and due to 8.1's changes I think that means it has to be built on 8.0.2.

**Comment by geekdenz** [comment]
Couldn't you just do the steps I outlined in NB 8.0?

**Comment by jeffrey-easyesi** [comment]
But there are no module issues when the project is opened in 8.0.2. If I did somehow import 8.1's new modules, it wouldn't build in 8.0.2, and even if I could force it to build the .nbm wouldn't install in 8.0.2.

**Comment by geekdenz** [comment]
OK. Then this is a non-issue.
