### ISSUE TITLE
Broken File Types: Editing Code Templates in Options

### ISSUE THREAD

**Issue by geekdenz** [Everlaw/nbts#17]
When clicking on Tools -> Options (or Preferences) and selecting Editor -> Code Templates, there is no TypeScript option.

**Comment by geekdenz** [comment]
Tried fixing this but unsuccessful. Is this possibly a bug in NB 8.1 RC? Cannot see what I'm doing wrong. I followed https://platform.netbeans.org/tutorials/nbm-code-template.html pretty much to the letter and changed the mime type everywhere to text/x-typescript, but still won't get the Code Templates options in Preferences. Is there something obvious I'm missing?

**Comment by jeffrey-easyesi** [comment]
Fixed - the problem was that the language didn't have a display name ([this EditorSettings.getDefault().getLanguageName(mimeType) call](http://hg.netbeans.org/main/file/e5a2f3cf0214/editor.codetemplates/src/org/netbeans/lib/editor/codetemplates/storage/ui/CodeTemplatesModel.java#l110) would just return "text/typescript"). I've [adapted the resources/Bundle.properties file from javascript2.editor](https://github.com/Everlaw/nbts/commit/4f64b50a02bd942748debac26404e7975d8b829d) to give display names to all the things that should be customizable.

**Comment by geekdenz** [comment]
Brilliant! Awesome work!
