### ISSUE TITLE
Consider using syntactic/semantic classifications

### ISSUE THREAD

**Issue by DanielRosenwasser** [Everlaw/nbts#2]
TypeScript Services provides classifications that can be used for syntactic and semantic classifications. With any new features coming in, it would be less work for you if you managed to get things wired up and utilize that.

**Comment by jeffrey-easyesi** [comment]
NetBeans's JS highlighting makes several distinctions that services does not:
* definitions of functions, methods, etc. are bold; uses are not
* global variables are purple
* member variables (not methods) are green
* unused variables have a gray underline

The syntax highlighting code hasn't been a maintenance burden so far; it has changed very little since 1.4.

**Comment by everflux** [comment]
Perhaps the issue should be closed if it will not be implemented?

**Comment by DanielRosenwasser** [comment]
Yup, thanks @everflux.
