### ISSUE TITLE
tsd.json

### ISSUE THREAD

**Issue by stunaz** [Everlaw/nbts#28]
Hi!
Any possibility to specify the location of the tsd.json or the typing directory?
When I have the typings directory outside of the Site Root, I lose all reference of the external definitions types.

**Comment by jeffrey-easyesi** [comment]
NetBeans's indexing API only notifies of changes to files that are under a source root. I don't know any good way around this, so referencing files outside the root is not supported. (Without being able to track their changes, the plugin would have to read them from disk every time you make any change to the program, which would be slow)

**Comment by stunaz** [comment]
The tsd and tsconfig file change very rarely. tsconfig remains almost the same. tsd can change once a week, when we decide to add a new definition of file or try to update the existing ones. What changes often it is the current code. So the track of the tsconfig file or tsd or typing directory is not really necessary, that can be ondemand, what you think?

**Comment by jeffrey-easyesi** [comment]
In the latest release (1.8.10.0) you can now reference or import .ts files that are outside the source root or in an ignored directory.

**Comment by ManfredSteiner** [comment]
At the moment (version 2.1.4.0)  *tsconfig.json* must be located on source root directory. That's for my point of view the wrong place, because it is part of the build configuration. My feature request would be to give you the chance to define the location in the project properties (i.e. *JavaScript/TypeScript* category). The file should be visible in the project browser in the category *Important Files*
