### ISSUE TITLE
Recompile after external changes

### ISSUE THREAD

**Issue by everflux** [Everlaw/nbts#35]
It would be great if the compilation could be triggered by external changes, especially
- version control (git pull, git checkout
- local history changes (revert modifications etc)

**Comment by jeffrey-easyesi** [comment]
It should already work, as long as the change happens while the project is open.

**Comment by everflux** [comment]
I had the files changed while NB was closed. Perhaps something like timestamp checking when a project is opened could be done? (Or compiling everything when project is opened to force consistency?)

**Comment by everflux** [comment]
If possible it would be great if similar to maven (or custom grunt) task functionality "clean" and "compile/build all" would be provided. In that case it is easy to recover from external changes that are not detected.

**Comment by jeffrey-easyesi** [comment]
In 2.1.4.1 I've added a "compile file" command to each .ts file's context menu. But TypeScript's language service API isn't suited for compiling a whole project, since it takes a single input file and writes all affected output files. So calling it on every file in the project is potentially very inefficient when output files are shared.

Compile-on-save is really a convenience for testing small changes and shouldn't be the main way of building a project.
