### ISSUE TITLE
Feature Request - Implement and Override (i) icon like Java

### ISSUE THREAD

**Issue by belapie** [Everlaw/nbts#66]
Is there a way to have the small green (i) icon on the line number when a function is implemented from an interface or overridden from an abstract class ?

**Comment by belapie** [comment]
Can we also have the orange status indicator for the unused imports (on the line and in the top-right corner of the editor)?

**Comment by jeffrey-easyesi** [comment]
Unused imports are shown with a gray underline like other unused variables. The only reason they're yellow in Java is because the Java editor has hints that can auto fix them (if you go into the Hints settings and disable the "Organize imports" and "Unused import" hints, you can see the underlying gray underline).

**Comment by belapie** [comment]
I see the gray underline for the unused imports :+1: , but i was talking about the orange icon on the right of the scrollbar and the indicator (top-right corner).

If i am at the bottom of the file, it would be interesting if i can see that there is an unused import by seeing the orange indicator.

**Comment by jeffrey-easyesi** [comment]
Implement/override link is now implemented in v2.1.4.0.

Regarding unused imports: You can use the `"compilerOptions": { "noUnusedLocals": true }` option in tsconfig.json to make it an error if imports and other local vars go unused.
