### ISSUE TITLE
Please add hints with fixes like in java

### ISSUE THREAD

**Issue by Chris2011** [Everlaw/nbts#85]
I know there you can add a lot of hints with fixes with alt + enter on errors/warnings but for me atm I realized it for methos who has a return value like int or Object e.g. but I gave nothing back. I got this error:

![return-value](https://cloud.githubusercontent.com/assets/795658/22114116/9e81e67e-de68-11e6-9c45-b5580f654c5f.png)

what is correct, it is a correct error but when I hit alt + enter I got only the error message but no fixes like in java as you can see it here:

![return-value-java](https://cloud.githubusercontent.com/assets/795658/22114140/b4787e20-de68-11e6-9474-a8e354cf6922.png)

So it would be really great to have such hints + fixes like in java.

Regards

Chris

**Comment by Chris2011** [comment]
And for changing to void too.

**Comment by jeffrey-easyesi** [comment]
Code fixes are provided by the TypeScript language service at https://github.com/Microsoft/TypeScript/ 

As of 2.1.4 the only fixes available are inserting a missing `super()` call in a subclass's constructor, and moving a `super()` call above a `this` access. I did my part so that nbts does support these:

![fix](https://cloud.githubusercontent.com/assets/3847609/22129665/419ed9fa-de5c-11e6-8107-ea2ec41cc3a5.png)

If there's a particular code fix you want, go to https://github.com/Microsoft/TypeScript/issues and file a bug there (if nobody else has already).
