### ISSUE TITLE
build 2.1.5.3 from source on netbeans 8.2

### ISSUE THREAD

**Issue by jackiszhp** [Everlaw/nbts#94]
on netbeans 8.2, with 2.1.5.3 source code, the following library should be added:

parsing api indexing
common scripting language types
common scripting language api (new)
utilities api

still progress api, a class called handlerfactory can not be located anywhere.

===============
by the way, the source code can be built on netbeans 8.0.2.

**Comment by jeffrey-easyesi** [comment]
NetBeans 8.0.x, 8.1, and 8.2 are all source-incompatible because of some modules being split up. I have this plugin set up to build under 8.0.x because the resulting .nbm will work on all 3 versions. If I built under 8.2, the resulting .nbm would only install on 8.2.

If you want to build in a later version, you'll have to add the new modules yourself. ProgressHandleFactory is in the "Progress API - Swing - org.netbeans.api.progress.nb" module.

**Comment by jackiszhp** [comment]
Thanks for the info. I guess this is helpful for some people, I have already given up, I am using netbeans 8.0.2, so no problem for me.
